spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jrtp701_ish_db?useSSL=false&serverTimezone=UTC
    username: root
    password: Pspk#@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ppspk7263@gmail.com
    password: ljts mlxi xafi cofo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true

server:
  port: 7076

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
